fos_ck_editor:
    inline: true
    default_config: cs_item_config
    input_sync: true

    plugins:
        menubutton:
            path:     "/bundles/commsy/menubutton/"
            filename: "plugin.js"
        language:
            path:     "/bundles/commsy/language/"
            filename: "plugin.js"
        bidi:
            path:     "/bundles/commsy/bidi/"
            filename: "plugin.js"
        commsyhelp:
            path:     "/bundles/commsy/commsyhelp/"
            filename: "plugin.js"
        commsyimage:
            path:     "/bundles/commsy/commsyimage/"
            filename: "plugin.js"
        commsyaudio:
            path:     "/bundles/commsy/commsyaudio/"
            filename: "plugin.js"
        commsyvideo:
            path:     "/bundles/commsy/commsyvideo/"
            filename: "plugin.js"
        commsydocument:
            path:     "/bundles/commsy/commsydocument/"
            filename: "plugin.js"
        tableresize:
            path:     "/bundles/commsy/tableresize/"
            filename: "plugin.js"
        sharedspace:
            path:     "/bundles/commsy/sharedspace/"
            filename: "plugin.js"
        widget:
            path:     "/bundles/commsy/widget/"
            filename: "plugin.js"
        lineutils:
            path:     "/bundles/commsy/lineutils/"
            filename: "plugin.js"
        widgetselection:
            path:     "/bundles/commsy/widgetselection/"
            filename: "plugin.js"
        sourcedialog:
            path:     "/bundles/commsy/sourcedialog/"
            filename: "plugin.js"

    toolbars:
        configs:
            simpleToolbar: [ "@clipboard", "@basicstyles" ]
            fullToolbar: [ [ "html5audio" ], "@clipboard", "@basicstyles" , "@paragraph", "@justify", "@misc", "/", "@format", "@style", "@content", "@language", "@commsy" ]
        items:
            clipboard: [ "Cut", "Copy", "Paste", "PasteFromWord", "Undo", "Redo" ]
            basicstyles: [ "Bold", "Italic", "Underline", "Strike", "Subscript", "Superscript" ]
            paragraph: [ "NumberedList", "BulletedList", "Outdent", "Indent", "Blockquote" ]
            justify: [ "JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock" ]
            misc: [ "Sourcedialog" ]
            format: [ "Format", "Font", "FontSize" ]
            style: [ "TextColor", "BGColor", "RemoveFormat" ]
            content: [ "Link", "Unlink", "Table", "HorizontalRule" ]
            language: [ "Language", "BidiLtr", "BidiRtl" ]
            commsy: [ "Commsyimage", "Commsyvideo", "Commsyaudio", "Commsydocument", "Commsyhelp" ]

    configs:
        cs_item_config:
            toolbar: "fullToolbar"
            extraPlugins: "sourcedialog,lineutils,widgetselection,sharedspace,widget,menubutton,language,bidi,tabletools,commsyvideo,commsyimage,commsyaudio,commsydocument,commsyhelp"
            language_list: ['de:German', 'en:English']
            removePlugins: 'floatingspace,maximize,resize'
            sharedSpaces:
                top: 'cke_top'
                bottom: 'cke_bottom'

        cs_annotation_config:
            toolbar: "simpleToolbar"
                