commsy:
    # Autosaving
    autosave:
        # possible modes: 0 -> unvisible, 1 -> verbose / silent, 2 -> verbose / counter
        mode: 0

        # limit in minutes
        limit: 6

        # # if ( !empty($c_session_lifetime) ) {
        # #    $c_autosave_limit = $c_session_lifetime-0.2;
        # # }

    # Connection to Beluga, the library system of the university of hamburg
    # Configuration needs with_ims_content_connection and ims_content_connection_temp_folder
    beluga:
        url_for_beluga_system: ~
        url_for_beluga_upload: ~

    # Use virus scanning at uploading files
    # ----------------------------------------------------
    # OPTION 1: there are performance lacks
    # scan file on upload
    # 1. installation
    #    on debian linux
    #    # apt-get install php5-clamavlib
    #    maybe you must edit /etc/php5/apache2/php.ini to active the clamavlib
    #    # /etc/init.d/apache2 restart
    # 2. enable virus scan at uploading files
    #    virus_scan = true;
    # 3. enable virus scan by php clamav library
    #    virus_use_php = true;
    #    
    # if you want to use another viren scanning tool
    # you must set the following variables
    # - only testet with clamav on linux
    #    virus_scan = true;
    #    virus_use_php = false;
    #    virus_scan_path = '/usr/bin';
    #    virus_scan_bin  = 'clamscan';
    # ----------------------------------------------------
    # OPTION 2: scan files with commsy cron
    # scan files every 24 hours
    # 1. installation
    #    on debian linux
    #    # apt-get install php5-clamavlib
    #    maybe you must edit /etc/php5/apache2/php.ini to active the clamavlib
    #    # /etc/init.d/apache2 restart
    # 2. enable virus scan at uploading files
    #    virus_scan_cron = true;
    # 3. enable virus scan by php clamav library
    #    virus_use_php = true;
    #
    # if you want to use another viren scanning tool
    # you must set the following variables
    # - only testet with clamav on linux
    #    virus_scan_cron = true;
    #    virus_use_php = false;
    #    virus_scan_path = '/usr/bin';
    #    virus_scan_bin  = 'clamscan';
    clamscan:
        virus_scan: false
        virus_use_php: false
        virus_scan_cron: false
        virus_scan_path: '/usr/bin'
        virus_scan_bin: 'clamscan'

    # Cookie management
    cookie:
        domain: ~
        path: ~

    # Database
    db:
        backup_prefix: 'zzz'

    # E-Mail
    email:
        from: '%email.from%'

    # E-Mail Upload
    upload:
        enabled: '%email.upload.enabled%'
        server: '%email.upload.server%'
        port: '%email.upload.port%'
        options: '%email.upload.options%'
        account: '%email.upload.account%'
        password: '%email.upload.password%'

    # Login
    login:
        shibboleth_direct_login: false
        shibboleth_redirect_url: ''
        shibboleth_deactivate_direct_login_by_portal_id: ''

    # Security
    security:
        # overwrite entries with "overwritten because of data security" when deleting a user
        # default = false
        # do nothing = true
        # set flag = flag
        privacy_disable_overwriting: '%security.privacy_disable_overwriting%'

        # allows all moderators to take over another user by default
        allow_moderator_takeover: true

    # Settings
    settings:
        # where to store the temporary export files
        export_temp_folder: 'var/temp/zip_export'

        # delete entries in database marked as deleted delete_days old
        delete_days: 182

        # session lifetime in hours
        session_lifetime: 6

        # proxy settings
        proxy_ip: '%proxy.ip%'
        proxy_port: '%proxy.port%'

        # single selection for categories
        single_cat_selection: false

        # temporary protect items from beeing editet by different users simultaneous
        item_locking: false

        # return path of emails
        # - "SENDER" will use sender email address as return path
        # - "mailreturn@your-domain.net" use the given email address
        # - "" do not use a return path
        return_path_mail_address: ''

    # Theming
    themes:
        # Default theme
        default: 'default'
        cs-date-color-no-color: ''
        cs-date-color-01: '#999999;'
        cs-date-color-02: '#CC0000;'
        cs-date-color-03: '#FF6600;'
        cs-date-color-04: '#FFCC00;'
        cs-date-color-05: '#FFFF66;'
        cs-date-color-06: '#33CC00;'
        cs-date-color-07: '#00CCCC;'
        cs-date-color-08: '#3366FF;'
        cs-date-color-09: '#6633FF;'
        cs-date-color-10: '#CC33CC;'

    # Wordpress
    wordpress:
        # for activating wordpress please set the following variable on true
        enabled: false

    # Limesurvey
    limesurvey:
        # set the following variable to activate limesurvey extension
        enabled: false

    # Etherpad
    etherpad:
        enabled: '%extensions.etherpad.enabled%'
        api_key: '%extensions.etherpad.api_key%'
        api_url: '%extensions.etherpad.api_url%'
        base_url: '%extensions.etherpad.base_url%'
        
    # mediawiki
    mediawiki:
        # set the following variable to activate mediawiki extension
        enabled: '%extensions.mediawiki.enabled%'
        url: '%extensions.mediawiki.url%'
        roomWikiUrl: '%extensions.mediawiki.room_wiki_url%'
        apiUrl: '%extensions.mediawiki.api_url%'
        consumerKey: '%extensions.mediawiki.consumer_key%'
        consumerSecret: '%extensions.mediawiki.consumer_secret%'
        accessToken: '%extensions.mediawiki.access_token%'
        accessSecret: '%extensions.mediawiki.access_secret%'

    # dates
    dates:
        timezone: '%dates.timezone%'