imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: commsy.yml }
    - { resource: fos_elastica.yml }
    - { resource: ckeditor.yml }
    - { resource: "@EtherpadBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    files_directory: '%kernel.root_dir%/../files'
    themes_directory: '%kernel.root_dir%/../web/css/themes'
    
framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        #handler_id:  session.handler.native_file
        #save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
        handler_id: ~
    fragments:       ~
    http_method_override: true
    assets:
        json_manifest_path: '%kernel.project_dir%/web/build/manifest.json'

sensio_framework_extra:
    router:
        annotations: false

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - CommsyBundle:form:uikit_layout.html.twig
        - LexikFormFilterBundle:Form:form_div_layout.html.twig
        - CommsyBundle:form:ckeditor_widget.html.twig
    globals:
        pre_definition: '%liip_theme_pre_configuration.active_theme%'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            mbarray: CommsyBundle\DBAL\Types\ArrayType
        mapping_types:
            enum: string
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

monolog:
    # handlers:
    #     commsy_request:
    #         type: service
    #         id: commsy.monolog.handler.doctrine_orm
    #         channels: [request]

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    port:      "%mailer_port%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Doctrine Migrations Configuration
doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

# LiipThemeBundle
liip_theme:
    themes:
        - default
        - football
        - stars
        - sun
        - ocean
        - schulcommsyhh
        - confetti
        - grey
        - darkblue
        - red
        - redgrey
        - uhh
    active_theme: 'default'
    assetic_integration: false

liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~
        commsy_user_image:
            quality: 100
            filters:
                thumbnail: { size: [200, 200], mode: outbound }
                
    loaders:
        default:
            filesystem:
                data_root: '%kernel.root_dir%/../files'

# KnpMenuBundle
knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: CommsyBundle:menu:knp_menu_sidebar.html.twig
        #template: knp_menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig

# KnpSnappyBundle
knp_snappy:
    #temporary_folder: %kernel.cache_dir%/snappy
    pdf:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltopdf #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\"" for Windows users
        options:    []
    image:
        enabled:    false
        binary:     /usr/local/bin/wkhtmltoimage #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\"" for Windows users
        options:    []

# RssAtomBundle
debril_rss_atom:
    private: true

# White october breadcrumbs
white_october_breadcrumbs:
    separator:      ''
    listClass:      'uk-breadcrumb'
    itemClass:      'uk-display-inline'