commsy_legacy:
    resource: "@CommsyLegacyBundle/Controller/"
    type:     annotation
    prefix:   /

commsy:
    resource: "@CommsyBundle/Controller/"
    type:     annotation
    prefix:   /

commsy_rss:
    path:     /rss/{contextId}/ 
    defaults: { _controller: DebrilRssAtomBundle:Stream:index, format: rss }
    prefix:   /

# liip_theme:
#     resource: "@LiipThemeBundle/Resources/config/routing.xml"
#     prefix: /theme

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"